### PR TITLE
fix QsqueryQueryData Data type for query results api call

### PR DESCRIPTION
**Pull request by peterbogdan**
Update type for Data as reflected here: https://github.com/jmpsec/osctrl/blob/main/logging/db.go#L54-L54

### CODE REVIEW

**Comment by peterbogdan** [comment]
@javuto should this be moved to https://github.com/jmpsec/osctrl/blob/main/types/osquery.go to avoid having to maintain multiple instances of the same type?

**Comment by javuto** [comment]
Hmmm in `osquery.go` we have the standard types for osquery, and the other one is our internal type to handle data serialization. I think it better stays in `db.go` since it is still our internal type.

**Comment by peterbogdan** [comment]
but would it better to be define the type in a single place and use that instead of redefining it in both `logging/db.go` and `api/postgres.go`?

to not keep 2 versions up to date when things are changing

**Comment by javuto** [comment]
Okay that makes sense, and it is better to only have to maintain that type in a single place. Would you add it in this PR? Thank you for working on it! 🙏

**Comment by peterbogdan** [comment]
updated

**Review by javuto — APPROVED** [review]

**Pull request merged**
